//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: osa.fbe
// FBE version: 1.10.0.0
//------------------------------------------------------------------------------

package osa.fbe;

// Fast Binary Encoding osa protocol version
public final class ProtocolVersion
{
    // Protocol major version
    public static final int Major = 0;
    // Protocol minor version
    public static final int Minor = 0;
}
