//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: osa.fbe
// FBE version: 1.10.0.0
//------------------------------------------------------------------------------

package osa

import "errors"
import "../fbe"

// Workaround for Go unused imports issue
var _ = errors.New
var _ = fbe.Version

// Fast Binary Encoding Simple field model
type FieldModelSimple struct {
    // Field model buffer
    buffer *fbe.Buffer
    // Field model buffer offset
    offset int

    Name *fbe.FieldModelString
    Depth *fbe.FieldModelInt32
    Sa *FieldModelArrayExtra
    Sex *FieldModelSex
}

// Create a new Simple field model
func NewFieldModelSimple(buffer *fbe.Buffer, offset int) *FieldModelSimple {
    fbeResult := FieldModelSimple{buffer: buffer, offset: offset}
    fbeResult.Name = fbe.NewFieldModelString(buffer, 4 + 4)
    fbeResult.Depth = fbe.NewFieldModelInt32(buffer, fbeResult.Name.FBEOffset() + fbeResult.Name.FBESize())
    fbeResult.Sa = NewFieldModelArrayExtra(buffer, fbeResult.Depth.FBEOffset() + fbeResult.Depth.FBESize(), 1)
    fbeResult.Sex = NewFieldModelSex(buffer, fbeResult.Sa.FBEOffset() + fbeResult.Sa.FBESize())
    return &fbeResult
}

// Get the field size
func (fm *FieldModelSimple) FBESize() int { return 4 }

// Get the field body size
func (fm *FieldModelSimple) FBEBody() int {
    fbeResult := 4 + 4 +
        fm.Name.FBESize() +
        fm.Depth.FBESize() +
        fm.Sa.FBESize() +
        fm.Sex.FBESize() +
        0
    return fbeResult
}

// Get the field extra size
func (fm *FieldModelSimple) FBEExtra() int {
    if (fm.buffer.Offset() + fm.FBEOffset() + fm.FBESize()) > fm.buffer.Size() {
        return 0
    }

    fbeStructOffset := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fm.FBEOffset()))
    if (fbeStructOffset == 0) || ((fm.buffer.Offset() + fbeStructOffset + 4) > fm.buffer.Size()) {
        return 0
    }

    fm.buffer.Shift(fbeStructOffset)

    fbeResult := fm.FBEBody() +
        fm.Name.FBEExtra() +
        fm.Depth.FBEExtra() +
        fm.Sa.FBEExtra() +
        fm.Sex.FBEExtra() +
        0

    fm.buffer.Unshift(fbeStructOffset)

    return fbeResult
}

// Get the field type
func (fm *FieldModelSimple) FBEType() int { return 2 }

// Get the field offset
func (fm *FieldModelSimple) FBEOffset() int { return fm.offset }
// Set the field offset
func (fm *FieldModelSimple) SetFBEOffset(value int) { fm.offset = value }

// Shift the current field offset
func (fm *FieldModelSimple) FBEShift(size int) { fm.offset += size }
// Unshift the current field offset
func (fm *FieldModelSimple) FBEUnshift(size int) { fm.offset -= size }

// Check if the struct value is valid
func (fm *FieldModelSimple) Verify() bool { return fm.VerifyType(true) }

// Check if the struct value and its type are valid
func (fm *FieldModelSimple) VerifyType(fbeVerifyType bool) bool {
    if (fm.buffer.Offset() + fm.FBEOffset() + fm.FBESize()) > fm.buffer.Size() {
        return true
    }

    fbeStructOffset := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fm.FBEOffset()))
    if (fbeStructOffset == 0) || ((fm.buffer.Offset() + fbeStructOffset + 4 + 4) > fm.buffer.Size()) {
        return false
    }

    fbeStructSize := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fbeStructOffset))
    if fbeStructSize < (4 + 4) {
        return false
    }

    fbeStructType := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fbeStructOffset + 4))
    if fbeVerifyType && (fbeStructType != fm.FBEType()) {
        return false
    }

    fm.buffer.Shift(fbeStructOffset)
    fbeResult := fm.VerifyFields(fbeStructSize)
    fm.buffer.Unshift(fbeStructOffset)
    return fbeResult
}

// // Check if the struct value fields are valid
func (fm *FieldModelSimple) VerifyFields(fbeStructSize int) bool {
    fbeCurrentSize := 4 + 4

    if (fbeCurrentSize + fm.Name.FBESize()) > fbeStructSize {
        return true
    }
    if !fm.Name.Verify() {
        return false
    }
    fbeCurrentSize += fm.Name.FBESize()

    if (fbeCurrentSize + fm.Depth.FBESize()) > fbeStructSize {
        return true
    }
    if !fm.Depth.Verify() {
        return false
    }
    fbeCurrentSize += fm.Depth.FBESize()

    if (fbeCurrentSize + fm.Sa.FBESize()) > fbeStructSize {
        return true
    }
    if !fm.Sa.Verify() {
        return false
    }
    fbeCurrentSize += fm.Sa.FBESize()

    if (fbeCurrentSize + fm.Sex.FBESize()) > fbeStructSize {
        return true
    }
    if !fm.Sex.Verify() {
        return false
    }
    fbeCurrentSize += fm.Sex.FBESize()

    return true
}

// Get the struct value (begin phase)
func (fm *FieldModelSimple) GetBegin() (int, error) {
    if (fm.buffer.Offset() + fm.FBEOffset() + fm.FBESize()) > fm.buffer.Size() {
        return 0, nil
    }

    fbeStructOffset := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fm.FBEOffset()))
    if (fbeStructOffset == 0) || ((fm.buffer.Offset() + fbeStructOffset + 4 + 4) > fm.buffer.Size()) {
        return 0, errors.New("model is broken")
    }

    fbeStructSize := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fbeStructOffset))
    if fbeStructSize < (4 + 4) {
        return 0, errors.New("model is broken")
    }

    fm.buffer.Shift(fbeStructOffset)
    return fbeStructOffset, nil
}

// Get the struct value (end phase)
func (fm *FieldModelSimple) GetEnd(fbeBegin int) {
    fm.buffer.Unshift(fbeBegin)
}

// Get the struct value
func (fm *FieldModelSimple) Get() (*Simple, error) {
    fbeResult := NewSimple()
    return fbeResult, fm.GetValue(fbeResult)
}

// Get the struct value by the given pointer
func (fm *FieldModelSimple) GetValue(fbeValue *Simple) error {
    fbeBegin, err := fm.GetBegin()
    if fbeBegin == 0 {
        return err
    }

    fbeStructSize := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset()))
    fm.GetFields(fbeValue, fbeStructSize)
    fm.GetEnd(fbeBegin)
    return nil
}

// Get the struct fields values
func (fm *FieldModelSimple) GetFields(fbeValue *Simple, fbeStructSize int) {
    fbeCurrentSize := 4 + 4

    if (fbeCurrentSize + fm.Name.FBESize()) <= fbeStructSize {
        fbeValue.Name, _ = fm.Name.Get()
    } else {
        fbeValue.Name = ""
    }
    fbeCurrentSize += fm.Name.FBESize()

    if (fbeCurrentSize + fm.Depth.FBESize()) <= fbeStructSize {
        fbeValue.Depth, _ = fm.Depth.Get()
    } else {
        fbeValue.Depth = 0
    }
    fbeCurrentSize += fm.Depth.FBESize()

    if (fbeCurrentSize + fm.Sa.FBESize()) <= fbeStructSize {
        slice, _ := fm.Sa.Get()
        copy(fbeValue.Sa[:], slice)
    } else {
        fbeValue.Sa = [1]Extra{}
    }
    fbeCurrentSize += fm.Sa.FBESize()

    if (fbeCurrentSize + fm.Sex.FBESize()) <= fbeStructSize {
        _ = fm.Sex.GetValue(&fbeValue.Sex)
    } else {
        fbeValue.Sex = *NewSex()
    }
    fbeCurrentSize += fm.Sex.FBESize()
}

// Set the struct value (begin phase)
func (fm *FieldModelSimple) SetBegin() (int, error) {
    if (fm.buffer.Offset() + fm.FBEOffset() + fm.FBESize()) > fm.buffer.Size() {
        return 0, errors.New("model is broken")
    }

    fbeStructSize := fm.FBEBody()
    fbeStructOffset := fm.buffer.Allocate(fbeStructSize) - fm.buffer.Offset()
    if (fbeStructOffset <= 0) || ((fm.buffer.Offset() + fbeStructOffset + fbeStructSize) > fm.buffer.Size()) {
        return 0, errors.New("model is broken")
    }

    fbe.WriteUInt32(fm.buffer.Data(), fm.buffer.Offset() + fm.FBEOffset(), uint32(fbeStructOffset))
    fbe.WriteUInt32(fm.buffer.Data(), fm.buffer.Offset() + fbeStructOffset, uint32(fbeStructSize))
    fbe.WriteUInt32(fm.buffer.Data(), fm.buffer.Offset() + fbeStructOffset + 4, uint32(fm.FBEType()))

    fm.buffer.Shift(fbeStructOffset)
    return fbeStructOffset, nil
}

// Set the struct value (end phase)
func (fm *FieldModelSimple) SetEnd(fbeBegin int) {
    fm.buffer.Unshift(fbeBegin)
}

// Set the struct value
func (fm *FieldModelSimple) Set(fbeValue *Simple) error {
    fbeBegin, err := fm.SetBegin()
    if fbeBegin == 0 {
        return err
    }

    err = fm.SetFields(fbeValue)
    fm.SetEnd(fbeBegin)
    return err
}

// Set the struct fields values
func (fm *FieldModelSimple) SetFields(fbeValue *Simple) error {
    var err error = nil

    if err = fm.Name.Set(fbeValue.Name); err != nil {
        return err
    }
    if err = fm.Depth.Set(fbeValue.Depth); err != nil {
        return err
    }
    if err = fm.Sa.Set(fbeValue.Sa[:]); err != nil {
        return err
    }
    if err = fm.Sex.Set(&fbeValue.Sex); err != nil {
        return err
    }
    return err
}
