//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: variants_ptr.fbe
// FBE version: 1.11.0.0
//------------------------------------------------------------------------------

package variants_ptr

import "fmt"
import "reflect"
import "errors"
import "fbeproj/proto/fbe"

// Workaround for Go unused imports issue
var _ = errors.New
var _ = fbe.Version

// FieldModelScalar1 variant field model
type FieldModelScalar1 struct {
    // Field model buffer
    buffer *fbe.Buffer
    // Field model buffer offset
    offset int
}

// Create a new FieldModelScalar1 variant field model
func NewFieldModelScalar1(buffer *fbe.Buffer, offset int) *FieldModelScalar1 {
    return &FieldModelScalar1{buffer: buffer, offset: offset}
}

// Get the field size
func (fm *FieldModelScalar1) FBESize() int { return 4 }

// Get the field body size
func (fm *FieldModelScalar1) FBEBody() int {
    // variant type's fbe_size not included
    // only variant_index included
    return 4
}

// Get the field extra size
func (fm *FieldModelScalar1) FBEExtra() int {
    if (fm.buffer.Offset() + fm.FBEOffset() + fm.FBESize()) > fm.buffer.Size() {
        return 0
    }

    fbeStructOffset := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fm.FBEOffset()))
    if (fbeStructOffset == 0) || ((fm.buffer.Offset() + fbeStructOffset + 4) > fm.buffer.Size()) {
        return 0
    }

    fm.buffer.Shift(fbeStructOffset)

    fbeResult := fm.FBEBody()

    fm.buffer.Unshift(fbeStructOffset)

    return fbeResult
}

// Get the field offset
func (fm *FieldModelScalar1) FBEOffset() int { return fm.offset }
// Set the field offset
func (fm *FieldModelScalar1) SetFBEOffset(value int) { fm.offset = value }

// Shift the current field offset
func (fm *FieldModelScalar1) FBEShift(size int) { fm.offset += size }
// Unshift the current field offset
func (fm *FieldModelScalar1) FBEUnshift(size int) { fm.offset -= size }

// Check if the value is valid
func (fm *FieldModelScalar1) Verify() bool {
    if (fm.buffer.Offset() + fm.FBEOffset() + fm.FBESize()) > fm.buffer.Size() {
        return false
    }

    fbeVariantOffset := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fm.FBEOffset()))
    if (fbeVariantOffset == 0) || ((fm.buffer.Offset() + fbeVariantOffset + 4) > fm.buffer.Size()) {
        return false
    }

    fbeVariantIndex := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fbeVariantOffset))
    if (fbeVariantIndex < 0 || fbeVariantIndex >= 4) {
        return false
    }

    fm.buffer.Shift(fbeVariantOffset)

    switch fbeVariantIndex {
    case 0:
        model := fbe.NewFieldModelBool(fm.buffer, 4)
        if !model.Verify() {
            return false
        }
        break
    case 1:
        model := fbe.NewFieldModelInt32(fm.buffer, 4)
        if !model.Verify() {
            return false
        }
        break
    case 2:
        model := fbe.NewFieldModelInt64(fm.buffer, 4)
        if !model.Verify() {
            return false
        }
        break
    case 3:
        model := fbe.NewFieldModelString(fm.buffer, 4)
        if !model.Verify() {
            return false
        }
        break
    }
    fm.buffer.Unshift(fbeVariantOffset)
    return true
}

// Get the struct value
func (fm *FieldModelScalar1) Get() (*Scalar1, error) {
    fbeResult := NewScalar1()
    return fbeResult, fm.GetValue(fbeResult)
}

// Get the struct value by the given pointer
func (fm *FieldModelScalar1) GetValue(fbeValue *Scalar1) error {
    if (fm.buffer.Offset() + fm.FBEOffset() + fm.FBESize()) > fm.buffer.Size() {
        return nil
    }

    fbeVariantOffset := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fm.FBEOffset()))
    if (fbeVariantOffset == 0) || ((fm.buffer.Offset() + fbeVariantOffset + 4) > fm.buffer.Size()) {
        return errors.New("model is broken")
    }

    fbeVariantIndex := int(fbe.ReadUInt32(fm.buffer.Data(), fm.buffer.Offset() + fbeVariantOffset))
    if (fbeVariantIndex < 0 || fbeVariantIndex >= 4) {
        return errors.New("model is broken")
    }

    fm.buffer.Shift(fbeVariantOffset)

    switch fbeVariantIndex {
    case 0:
        model := fbe.NewFieldModelBool(fm.buffer, 4)
        fbeValue.Value, _ = model.Get()
    case 1:
        model := fbe.NewFieldModelInt32(fm.buffer, 4)
        fbeValue.Value, _ = model.Get()
    case 2:
        model := fbe.NewFieldModelInt64(fm.buffer, 4)
        fbeValue.Value, _ = model.Get()
    case 3:
        model := fbe.NewFieldModelString(fm.buffer, 4)
        fbeValue.Value, _ = model.Get()
    default:
        return fmt.Errorf("unknown fbeVariantIndex: %d", fbeVariantIndex)
    }
    fm.buffer.Unshift(fbeVariantOffset)
    return nil
}


// Set the struct value (begin phase)
func (fm *FieldModelScalar1) SetBegin(variantTypeFBESize int, variantTypeIndex int) (int, error) {
    if (fm.buffer.Offset() + fm.FBEOffset() + fm.FBESize()) > fm.buffer.Size() {
        return 0, errors.New("model is broken")
    }

    fbeVariantSize := fm.FBEBody() + variantTypeFBESize
    fbeVariantOffset := fm.buffer.Allocate(fbeVariantSize) - fm.buffer.Offset()
    if (fbeVariantOffset <= 0) || ((fm.buffer.Offset() + fbeVariantOffset + fbeVariantSize) > fm.buffer.Size()) {
        return 0, errors.New("model is broken")
    }

    fbe.WriteUInt32(fm.buffer.Data(), fm.buffer.Offset() + fm.FBEOffset(), uint32(fbeVariantOffset))
    fbe.WriteUInt32(fm.buffer.Data(), fm.buffer.Offset() + fbeVariantOffset, uint32(variantTypeIndex))

    fm.buffer.Shift(fbeVariantOffset)
    return fbeVariantOffset, nil
}

// Set the struct value (end phase)
func (fm *FieldModelScalar1) SetEnd(fbeBegin int) {
    fm.buffer.Unshift(fbeBegin)
}

// Set the struct value
func (fm *FieldModelScalar1) Set(fbeValue *Scalar1) error {
    if (fm.buffer.Offset() + fm.FBEOffset() + fm.FBESize()) > fm.buffer.Size() {
        return errors.New("model is broken")
    }

    switch t := (fbeValue.Value).(type) {
    case bool:
        model := fbe.NewFieldModelBool(fm.buffer, 4)
        fbeBegin, err := fm.SetBegin(model.FBESize(), 0)
        if err != nil {
            return err
        }
        if fbeBegin == 0 {
            return nil
        }
        if err = model.Set(t); err != nil {
            return err
        }
        fm.SetEnd(fbeBegin)
    case int32:
        model := fbe.NewFieldModelInt32(fm.buffer, 4)
        fbeBegin, err := fm.SetBegin(model.FBESize(), 1)
        if err != nil {
            return err
        }
        if fbeBegin == 0 {
            return nil
        }
        if err = model.Set(t); err != nil {
            return err
        }
        fm.SetEnd(fbeBegin)
    case int64:
        model := fbe.NewFieldModelInt64(fm.buffer, 4)
        fbeBegin, err := fm.SetBegin(model.FBESize(), 2)
        if err != nil {
            return err
        }
        if fbeBegin == 0 {
            return nil
        }
        if err = model.Set(t); err != nil {
            return err
        }
        fm.SetEnd(fbeBegin)
    case string:
        model := fbe.NewFieldModelString(fm.buffer, 4)
        fbeBegin, err := fm.SetBegin(model.FBESize(), 3)
        if err != nil {
            return err
        }
        if fbeBegin == 0 {
            return nil
        }
        if err = model.Set(t); err != nil {
            return err
        }
        fm.SetEnd(fbeBegin)
    default:
        return fmt.Errorf("unsupported variant type: %s", reflect.TypeOf(t).String())
    }

    return nil
}
