//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: variants.fbe
// FBE version: 1.10.0.0
//------------------------------------------------------------------------------

package variants.fbe;

// Fast Binary Encoding variants protocol version
public final class ProtocolVersion
{
    // Protocol major version
    public static final int Major = 0;
    // Protocol minor version
    public static final int Minor = 0;
}
