//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: variants.fbe
// FBE version: 1.10.0.0
//------------------------------------------------------------------------------

package variants.fbe;

// Fast Binary Encoding variants receiver
public class Receiver extends fbe.Receiver
{
    // Receiver values accessors

    // Receiver models accessors

    public Receiver()
    {
        super(false);
    }
    public Receiver(fbe.Buffer buffer)
    {
        super(buffer, false);
    }

    // Receive handlers

    @Override
    public boolean onReceive(long type, byte[] buffer, long offset, long size)
    {
        switch ((int)type)
        {
            default: break;
        }

        return false;
    }
}
