//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: protoex.fbe
// FBE version: 1.11.0.0
//------------------------------------------------------------------------------

#include "protoex_final_pmr_models.h"

namespace FBE {

FinalModel<::protoex_pmr::Order>::FinalModel(FBEBuffer& buffer, size_t offset) noexcept : _buffer(buffer), _offset(offset)
    , id(buffer, 0)
    , symbol(buffer, 0)
    , side(buffer, 0)
    , type(buffer, 0)
    , price(buffer, 0)
    , volume(buffer, 0)
    , tp(buffer, 0)
    , sl(buffer, 0)
{}

size_t FinalModel<::protoex_pmr::Order>::fbe_allocation_size(const ::protoex_pmr::Order& fbe_value) const noexcept
{
    size_t fbe_result = 0
        + id.fbe_allocation_size(fbe_value.id)
        + symbol.fbe_allocation_size(fbe_value.symbol)
        + side.fbe_allocation_size(fbe_value.side)
        + type.fbe_allocation_size(fbe_value.type)
        + price.fbe_allocation_size(fbe_value.price)
        + volume.fbe_allocation_size(fbe_value.volume)
        + tp.fbe_allocation_size(fbe_value.tp)
        + sl.fbe_allocation_size(fbe_value.sl)
        ;
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Order>::verify() const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = verify_fields();
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Order>::verify_fields() const noexcept
{
    size_t fbe_current_offset = 0;
    [[maybe_unused]] size_t fbe_field_size;

    // Inline verify of int32 field id (4 bytes)
    if ((_buffer.offset() + fbe_current_offset + 4) > _buffer.size())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += 4;

    symbol.fbe_offset(fbe_current_offset);
    fbe_field_size = symbol.verify();
    if (fbe_field_size == std::numeric_limits<std::size_t>::max())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += fbe_field_size;

    // Batch verify 6 fixed-size fields (34 bytes)
    {
        if ((_buffer.offset() + fbe_current_offset + 34) > _buffer.size())
            return std::numeric_limits<std::size_t>::max();
        fbe_current_offset += 34;
    }

    return fbe_current_offset;
}

size_t FinalModel<::protoex_pmr::Order>::get(::protoex_pmr::Order& fbe_value) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Order>::get_fields([[maybe_unused]] ::protoex_pmr::Order& fbe_value) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    // Inline read of int32 field id (4 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        if ((fbe_field_offset + 4) > _buffer.size())
            return 0;
        fbe_value.id = unaligned_load<int32_t>(_buffer.data() + fbe_field_offset);
        fbe_current_offset += 4;
        fbe_current_size += 4;
    }

    symbol.fbe_offset(fbe_current_offset);
    fbe_field_size = symbol.get(fbe_value.symbol);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    // Batch read 6 fixed-size fields (34 bytes)
    {
        size_t fbe_batch_offset = _buffer.offset() + fbe_current_offset;
        if ((fbe_batch_offset + 34) > _buffer.size())
            return 0;
        const uint8_t* fbe_batch_ptr = _buffer.data() + fbe_batch_offset;
        fbe_value.side = static_cast<decltype(fbe_value.side)>(unaligned_load<uint8_t>(fbe_batch_ptr + 0));
        fbe_value.type = static_cast<decltype(fbe_value.type)>(unaligned_load<uint8_t>(fbe_batch_ptr + 1));
        fbe_value.price = unaligned_load<double>(fbe_batch_ptr + 2);
        fbe_value.volume = unaligned_load<double>(fbe_batch_ptr + 10);
        fbe_value.tp = unaligned_load<double>(fbe_batch_ptr + 18);
        fbe_value.sl = unaligned_load<double>(fbe_batch_ptr + 26);
        fbe_current_offset += 34;
        fbe_current_size += 34;
    }

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::Order>::get(::protoex_pmr::Order& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value, resource);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Order>::get_fields([[maybe_unused]] ::protoex_pmr::Order& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    // Inline read of int32 field id (4 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        if ((fbe_field_offset + 4) > _buffer.size())
            return 0;
        fbe_value.id = unaligned_load<int32_t>(_buffer.data() + fbe_field_offset);
        fbe_current_offset += 4;
        fbe_current_size += 4;
    }

    symbol.fbe_offset(fbe_current_offset);
    fbe_field_size = symbol.get(fbe_value.symbol, resource);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    // Batch read 6 fixed-size fields (34 bytes)
    {
        size_t fbe_batch_offset = _buffer.offset() + fbe_current_offset;
        if ((fbe_batch_offset + 34) > _buffer.size())
            return 0;
        const uint8_t* fbe_batch_ptr = _buffer.data() + fbe_batch_offset;
        fbe_value.side = static_cast<decltype(fbe_value.side)>(unaligned_load<uint8_t>(fbe_batch_ptr + 0));
        fbe_value.type = static_cast<decltype(fbe_value.type)>(unaligned_load<uint8_t>(fbe_batch_ptr + 1));
        fbe_value.price = unaligned_load<double>(fbe_batch_ptr + 2);
        fbe_value.volume = unaligned_load<double>(fbe_batch_ptr + 10);
        fbe_value.tp = unaligned_load<double>(fbe_batch_ptr + 18);
        fbe_value.sl = unaligned_load<double>(fbe_batch_ptr + 26);
        fbe_current_offset += 34;
        fbe_current_size += 34;
    }

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::Order>::set(const ::protoex_pmr::Order& fbe_value) noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = set_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Order>::set_fields([[maybe_unused]] const ::protoex_pmr::Order& fbe_value) noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    // Inline write of int32 field id (4 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        assert(((fbe_field_offset + 4) <= _buffer.size()) && "Model is broken!");
        if ((fbe_field_offset + 4) > _buffer.size())
            return 0;
        unaligned_store<int32_t>(_buffer.data() + fbe_field_offset, fbe_value.id);
        fbe_current_offset += 4;
        fbe_current_size += 4;
    }

    symbol.fbe_offset(fbe_current_offset);
    fbe_field_size = symbol.set(fbe_value.symbol);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    // Batch write 6 fixed-size fields (34 bytes)
    {
        size_t fbe_batch_offset = _buffer.offset() + fbe_current_offset;
        assert(((fbe_batch_offset + 34) <= _buffer.size()) && "Model is broken!");
        if ((fbe_batch_offset + 34) > _buffer.size())
            return 0;
        uint8_t* fbe_batch_ptr = _buffer.data() + fbe_batch_offset;
        unaligned_store<uint8_t>(fbe_batch_ptr + 0, static_cast<uint8_t>(fbe_value.side));
        unaligned_store<uint8_t>(fbe_batch_ptr + 1, static_cast<uint8_t>(fbe_value.type));
        unaligned_store<double>(fbe_batch_ptr + 2, fbe_value.price);
        unaligned_store<double>(fbe_batch_ptr + 10, fbe_value.volume);
        unaligned_store<double>(fbe_batch_ptr + 18, fbe_value.tp);
        unaligned_store<double>(fbe_batch_ptr + 26, fbe_value.sl);
        fbe_current_offset += 34;
        fbe_current_size += 34;
    }

    return fbe_current_size;
}

namespace protoex_pmr {

bool OrderFinalModel::verify()
{
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return false;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return false;

    return ((8 + _model.verify()) == fbe_struct_size);
}

size_t OrderFinalModel::serialize(const ::protoex_pmr::Order& value)
{
    size_t fbe_initial_size = this->buffer().size();

    uint32_t fbe_struct_type = (uint32_t)fbe_type();
    uint32_t fbe_struct_size = (uint32_t)(8 + _model.fbe_allocation_size(value));
    uint32_t fbe_struct_offset = (uint32_t)(this->buffer().allocate(fbe_struct_size) - this->buffer().offset());
    assert(((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) > this->buffer().size())
        return 0;

    fbe_struct_size = (uint32_t)(8 + _model.set(value));
    this->buffer().resize(fbe_initial_size + fbe_struct_size);

    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8, fbe_struct_size);
    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4, fbe_struct_type);

    return fbe_struct_size;
}

size_t OrderFinalModel::deserialize(::protoex_pmr::Order& value) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value);
}

size_t OrderFinalModel::deserialize(::protoex_pmr::Order& value, std::pmr::memory_resource* resource) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value, resource);
}

} // namespace protoex_pmr

FinalModel<::protoex_pmr::Balance>::FinalModel(FBEBuffer& buffer, size_t offset) noexcept : _buffer(buffer), _offset(offset)
    , parent(buffer, 0)
    , locked(buffer, 0)
{}

size_t FinalModel<::protoex_pmr::Balance>::fbe_allocation_size(const ::protoex_pmr::Balance& fbe_value) const noexcept
{
    size_t fbe_result = 0
        + parent.fbe_allocation_size(fbe_value)
        + locked.fbe_allocation_size(fbe_value.locked)
        ;
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Balance>::verify() const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = verify_fields();
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Balance>::verify_fields() const noexcept
{
    size_t fbe_current_offset = 0;
    [[maybe_unused]] size_t fbe_field_size;

    parent.fbe_offset(fbe_current_offset);
    fbe_field_size = parent.verify_fields();
    if (fbe_field_size == std::numeric_limits<std::size_t>::max())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += fbe_field_size;

    // Inline verify of double field locked (8 bytes)
    if ((_buffer.offset() + fbe_current_offset + 8) > _buffer.size())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += 8;

    return fbe_current_offset;
}

size_t FinalModel<::protoex_pmr::Balance>::get(::protoex_pmr::Balance& fbe_value) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Balance>::get_fields([[maybe_unused]] ::protoex_pmr::Balance& fbe_value) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    parent.fbe_offset(fbe_current_offset);
    fbe_field_size = parent.get_fields(fbe_value);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    // Inline read of double field locked (8 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        if ((fbe_field_offset + 8) > _buffer.size())
            return 0;
        fbe_value.locked = unaligned_load<double>(_buffer.data() + fbe_field_offset);
        fbe_current_offset += 8;
        fbe_current_size += 8;
    }

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::Balance>::get(::protoex_pmr::Balance& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value, resource);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Balance>::get_fields([[maybe_unused]] ::protoex_pmr::Balance& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    parent.fbe_offset(fbe_current_offset);
    fbe_field_size = parent.get_fields(fbe_value, resource);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    // Inline read of double field locked (8 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        if ((fbe_field_offset + 8) > _buffer.size())
            return 0;
        fbe_value.locked = unaligned_load<double>(_buffer.data() + fbe_field_offset);
        fbe_current_offset += 8;
        fbe_current_size += 8;
    }

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::Balance>::set(const ::protoex_pmr::Balance& fbe_value) noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = set_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Balance>::set_fields([[maybe_unused]] const ::protoex_pmr::Balance& fbe_value) noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    parent.fbe_offset(fbe_current_offset);
    fbe_field_size = parent.set_fields(fbe_value);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    // Inline write of double field locked (8 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        assert(((fbe_field_offset + 8) <= _buffer.size()) && "Model is broken!");
        if ((fbe_field_offset + 8) > _buffer.size())
            return 0;
        unaligned_store<double>(_buffer.data() + fbe_field_offset, fbe_value.locked);
        fbe_current_offset += 8;
        fbe_current_size += 8;
    }

    return fbe_current_size;
}

namespace protoex_pmr {

bool BalanceFinalModel::verify()
{
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return false;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return false;

    return ((8 + _model.verify()) == fbe_struct_size);
}

size_t BalanceFinalModel::serialize(const ::protoex_pmr::Balance& value)
{
    size_t fbe_initial_size = this->buffer().size();

    uint32_t fbe_struct_type = (uint32_t)fbe_type();
    uint32_t fbe_struct_size = (uint32_t)(8 + _model.fbe_allocation_size(value));
    uint32_t fbe_struct_offset = (uint32_t)(this->buffer().allocate(fbe_struct_size) - this->buffer().offset());
    assert(((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) > this->buffer().size())
        return 0;

    fbe_struct_size = (uint32_t)(8 + _model.set(value));
    this->buffer().resize(fbe_initial_size + fbe_struct_size);

    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8, fbe_struct_size);
    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4, fbe_struct_type);

    return fbe_struct_size;
}

size_t BalanceFinalModel::deserialize(::protoex_pmr::Balance& value) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value);
}

size_t BalanceFinalModel::deserialize(::protoex_pmr::Balance& value, std::pmr::memory_resource* resource) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value, resource);
}

} // namespace protoex_pmr

FinalModel<::protoex_pmr::Account>::FinalModel(FBEBuffer& buffer, size_t offset) noexcept : _buffer(buffer), _offset(offset)
    , id(buffer, 0)
    , name(buffer, 0)
    , state(buffer, 0)
    , wallet(buffer, 0)
    , asset(buffer, 0)
    , orders(buffer, 0)
{}

size_t FinalModel<::protoex_pmr::Account>::fbe_allocation_size(const ::protoex_pmr::Account& fbe_value) const noexcept
{
    size_t fbe_result = 0
        + id.fbe_allocation_size(fbe_value.id)
        + name.fbe_allocation_size(fbe_value.name)
        + state.fbe_allocation_size(fbe_value.state)
        + wallet.fbe_allocation_size(fbe_value.wallet)
        + asset.fbe_allocation_size(fbe_value.asset)
        + orders.fbe_allocation_size(fbe_value.orders)
        ;
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Account>::verify() const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = verify_fields();
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Account>::verify_fields() const noexcept
{
    size_t fbe_current_offset = 0;
    [[maybe_unused]] size_t fbe_field_size;

    // Inline verify of int32 field id (4 bytes)
    if ((_buffer.offset() + fbe_current_offset + 4) > _buffer.size())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += 4;

    name.fbe_offset(fbe_current_offset);
    fbe_field_size = name.verify();
    if (fbe_field_size == std::numeric_limits<std::size_t>::max())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += fbe_field_size;

    // Inline verify of StateEx field state (1 bytes)
    if ((_buffer.offset() + fbe_current_offset + 1) > _buffer.size())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += 1;

    wallet.fbe_offset(fbe_current_offset);
    fbe_field_size = wallet.verify();
    if (fbe_field_size == std::numeric_limits<std::size_t>::max())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += fbe_field_size;

    asset.fbe_offset(fbe_current_offset);
    fbe_field_size = asset.verify();
    if (fbe_field_size == std::numeric_limits<std::size_t>::max())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += fbe_field_size;

    orders.fbe_offset(fbe_current_offset);
    fbe_field_size = orders.verify();
    if (fbe_field_size == std::numeric_limits<std::size_t>::max())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += fbe_field_size;

    return fbe_current_offset;
}

size_t FinalModel<::protoex_pmr::Account>::get(::protoex_pmr::Account& fbe_value) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Account>::get_fields([[maybe_unused]] ::protoex_pmr::Account& fbe_value) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    // Inline read of int32 field id (4 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        if ((fbe_field_offset + 4) > _buffer.size())
            return 0;
        fbe_value.id = unaligned_load<int32_t>(_buffer.data() + fbe_field_offset);
        fbe_current_offset += 4;
        fbe_current_size += 4;
    }

    name.fbe_offset(fbe_current_offset);
    fbe_field_size = name.get(fbe_value.name);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    // Inline read of StateEx field state (1 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        if ((fbe_field_offset + 1) > _buffer.size())
            return 0;
        fbe_value.state = static_cast<decltype(fbe_value.state)>(unaligned_load<uint8_t>(_buffer.data() + fbe_field_offset));
        fbe_current_offset += 1;
        fbe_current_size += 1;
    }

    wallet.fbe_offset(fbe_current_offset);
    fbe_field_size = wallet.get(fbe_value.wallet);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    asset.fbe_offset(fbe_current_offset);
    fbe_field_size = asset.get(fbe_value.asset);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    orders.fbe_offset(fbe_current_offset);
    fbe_field_size = orders.get(fbe_value.orders);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::Account>::get(::protoex_pmr::Account& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value, resource);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Account>::get_fields([[maybe_unused]] ::protoex_pmr::Account& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    // Inline read of int32 field id (4 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        if ((fbe_field_offset + 4) > _buffer.size())
            return 0;
        fbe_value.id = unaligned_load<int32_t>(_buffer.data() + fbe_field_offset);
        fbe_current_offset += 4;
        fbe_current_size += 4;
    }

    name.fbe_offset(fbe_current_offset);
    fbe_field_size = name.get(fbe_value.name, resource);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    // Inline read of StateEx field state (1 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        if ((fbe_field_offset + 1) > _buffer.size())
            return 0;
        fbe_value.state = static_cast<decltype(fbe_value.state)>(unaligned_load<uint8_t>(_buffer.data() + fbe_field_offset));
        fbe_current_offset += 1;
        fbe_current_size += 1;
    }

    wallet.fbe_offset(fbe_current_offset);
    fbe_field_size = wallet.get(fbe_value.wallet, resource);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    asset.fbe_offset(fbe_current_offset);
    fbe_field_size = asset.get(fbe_value.asset, resource);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    orders.fbe_offset(fbe_current_offset);
    fbe_field_size = orders.get(fbe_value.orders, resource);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::Account>::set(const ::protoex_pmr::Account& fbe_value) noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = set_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::Account>::set_fields([[maybe_unused]] const ::protoex_pmr::Account& fbe_value) noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    // Inline write of int32 field id (4 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        assert(((fbe_field_offset + 4) <= _buffer.size()) && "Model is broken!");
        if ((fbe_field_offset + 4) > _buffer.size())
            return 0;
        unaligned_store<int32_t>(_buffer.data() + fbe_field_offset, fbe_value.id);
        fbe_current_offset += 4;
        fbe_current_size += 4;
    }

    name.fbe_offset(fbe_current_offset);
    fbe_field_size = name.set(fbe_value.name);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    // Inline write of StateEx field state (1 bytes)
    {
        size_t fbe_field_offset = _buffer.offset() + fbe_current_offset;
        assert(((fbe_field_offset + 1) <= _buffer.size()) && "Model is broken!");
        if ((fbe_field_offset + 1) > _buffer.size())
            return 0;
        unaligned_store<uint8_t>(_buffer.data() + fbe_field_offset, static_cast<uint8_t>(fbe_value.state));
        fbe_current_offset += 1;
        fbe_current_size += 1;
    }

    wallet.fbe_offset(fbe_current_offset);
    fbe_field_size = wallet.set(fbe_value.wallet);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    asset.fbe_offset(fbe_current_offset);
    fbe_field_size = asset.set(fbe_value.asset);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    orders.fbe_offset(fbe_current_offset);
    fbe_field_size = orders.set(fbe_value.orders);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

namespace protoex_pmr {

bool AccountFinalModel::verify()
{
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return false;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return false;

    return ((8 + _model.verify()) == fbe_struct_size);
}

size_t AccountFinalModel::serialize(const ::protoex_pmr::Account& value)
{
    size_t fbe_initial_size = this->buffer().size();

    uint32_t fbe_struct_type = (uint32_t)fbe_type();
    uint32_t fbe_struct_size = (uint32_t)(8 + _model.fbe_allocation_size(value));
    uint32_t fbe_struct_offset = (uint32_t)(this->buffer().allocate(fbe_struct_size) - this->buffer().offset());
    assert(((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) > this->buffer().size())
        return 0;

    fbe_struct_size = (uint32_t)(8 + _model.set(value));
    this->buffer().resize(fbe_initial_size + fbe_struct_size);

    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8, fbe_struct_size);
    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4, fbe_struct_type);

    return fbe_struct_size;
}

size_t AccountFinalModel::deserialize(::protoex_pmr::Account& value) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value);
}

size_t AccountFinalModel::deserialize(::protoex_pmr::Account& value, std::pmr::memory_resource* resource) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value, resource);
}

} // namespace protoex_pmr

FinalModel<::protoex_pmr::OrderMessage>::FinalModel(FBEBuffer& buffer, size_t offset) noexcept : _buffer(buffer), _offset(offset)
    , body(buffer, 0)
{}

size_t FinalModel<::protoex_pmr::OrderMessage>::fbe_allocation_size(const ::protoex_pmr::OrderMessage& fbe_value) const noexcept
{
    size_t fbe_result = 0
        + body.fbe_allocation_size(fbe_value.body)
        ;
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::OrderMessage>::verify() const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = verify_fields();
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::OrderMessage>::verify_fields() const noexcept
{
    size_t fbe_current_offset = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.verify();
    if (fbe_field_size == std::numeric_limits<std::size_t>::max())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += fbe_field_size;

    return fbe_current_offset;
}

size_t FinalModel<::protoex_pmr::OrderMessage>::get(::protoex_pmr::OrderMessage& fbe_value) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::OrderMessage>::get_fields([[maybe_unused]] ::protoex_pmr::OrderMessage& fbe_value) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.get(fbe_value.body);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::OrderMessage>::get(::protoex_pmr::OrderMessage& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value, resource);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::OrderMessage>::get_fields([[maybe_unused]] ::protoex_pmr::OrderMessage& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.get(fbe_value.body, resource);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::OrderMessage>::set(const ::protoex_pmr::OrderMessage& fbe_value) noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = set_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::OrderMessage>::set_fields([[maybe_unused]] const ::protoex_pmr::OrderMessage& fbe_value) noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.set(fbe_value.body);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

namespace protoex_pmr {

bool OrderMessageFinalModel::verify()
{
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return false;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return false;

    return ((8 + _model.verify()) == fbe_struct_size);
}

size_t OrderMessageFinalModel::serialize(const ::protoex_pmr::OrderMessage& value)
{
    size_t fbe_initial_size = this->buffer().size();

    uint32_t fbe_struct_type = (uint32_t)fbe_type();
    uint32_t fbe_struct_size = (uint32_t)(8 + _model.fbe_allocation_size(value));
    uint32_t fbe_struct_offset = (uint32_t)(this->buffer().allocate(fbe_struct_size) - this->buffer().offset());
    assert(((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) > this->buffer().size())
        return 0;

    fbe_struct_size = (uint32_t)(8 + _model.set(value));
    this->buffer().resize(fbe_initial_size + fbe_struct_size);

    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8, fbe_struct_size);
    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4, fbe_struct_type);

    return fbe_struct_size;
}

size_t OrderMessageFinalModel::deserialize(::protoex_pmr::OrderMessage& value) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value);
}

size_t OrderMessageFinalModel::deserialize(::protoex_pmr::OrderMessage& value, std::pmr::memory_resource* resource) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value, resource);
}

} // namespace protoex_pmr

FinalModel<::protoex_pmr::BalanceMessage>::FinalModel(FBEBuffer& buffer, size_t offset) noexcept : _buffer(buffer), _offset(offset)
    , body(buffer, 0)
{}

size_t FinalModel<::protoex_pmr::BalanceMessage>::fbe_allocation_size(const ::protoex_pmr::BalanceMessage& fbe_value) const noexcept
{
    size_t fbe_result = 0
        + body.fbe_allocation_size(fbe_value.body)
        ;
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::BalanceMessage>::verify() const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = verify_fields();
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::BalanceMessage>::verify_fields() const noexcept
{
    size_t fbe_current_offset = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.verify();
    if (fbe_field_size == std::numeric_limits<std::size_t>::max())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += fbe_field_size;

    return fbe_current_offset;
}

size_t FinalModel<::protoex_pmr::BalanceMessage>::get(::protoex_pmr::BalanceMessage& fbe_value) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::BalanceMessage>::get_fields([[maybe_unused]] ::protoex_pmr::BalanceMessage& fbe_value) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.get(fbe_value.body);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::BalanceMessage>::get(::protoex_pmr::BalanceMessage& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value, resource);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::BalanceMessage>::get_fields([[maybe_unused]] ::protoex_pmr::BalanceMessage& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.get(fbe_value.body, resource);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::BalanceMessage>::set(const ::protoex_pmr::BalanceMessage& fbe_value) noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = set_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::BalanceMessage>::set_fields([[maybe_unused]] const ::protoex_pmr::BalanceMessage& fbe_value) noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.set(fbe_value.body);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

namespace protoex_pmr {

bool BalanceMessageFinalModel::verify()
{
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return false;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return false;

    return ((8 + _model.verify()) == fbe_struct_size);
}

size_t BalanceMessageFinalModel::serialize(const ::protoex_pmr::BalanceMessage& value)
{
    size_t fbe_initial_size = this->buffer().size();

    uint32_t fbe_struct_type = (uint32_t)fbe_type();
    uint32_t fbe_struct_size = (uint32_t)(8 + _model.fbe_allocation_size(value));
    uint32_t fbe_struct_offset = (uint32_t)(this->buffer().allocate(fbe_struct_size) - this->buffer().offset());
    assert(((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) > this->buffer().size())
        return 0;

    fbe_struct_size = (uint32_t)(8 + _model.set(value));
    this->buffer().resize(fbe_initial_size + fbe_struct_size);

    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8, fbe_struct_size);
    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4, fbe_struct_type);

    return fbe_struct_size;
}

size_t BalanceMessageFinalModel::deserialize(::protoex_pmr::BalanceMessage& value) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value);
}

size_t BalanceMessageFinalModel::deserialize(::protoex_pmr::BalanceMessage& value, std::pmr::memory_resource* resource) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value, resource);
}

} // namespace protoex_pmr

FinalModel<::protoex_pmr::AccountMessage>::FinalModel(FBEBuffer& buffer, size_t offset) noexcept : _buffer(buffer), _offset(offset)
    , body(buffer, 0)
{}

size_t FinalModel<::protoex_pmr::AccountMessage>::fbe_allocation_size(const ::protoex_pmr::AccountMessage& fbe_value) const noexcept
{
    size_t fbe_result = 0
        + body.fbe_allocation_size(fbe_value.body)
        ;
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::AccountMessage>::verify() const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = verify_fields();
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::AccountMessage>::verify_fields() const noexcept
{
    size_t fbe_current_offset = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.verify();
    if (fbe_field_size == std::numeric_limits<std::size_t>::max())
        return std::numeric_limits<std::size_t>::max();
    fbe_current_offset += fbe_field_size;

    return fbe_current_offset;
}

size_t FinalModel<::protoex_pmr::AccountMessage>::get(::protoex_pmr::AccountMessage& fbe_value) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::AccountMessage>::get_fields([[maybe_unused]] ::protoex_pmr::AccountMessage& fbe_value) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.get(fbe_value.body);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::AccountMessage>::get(::protoex_pmr::AccountMessage& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = get_fields(fbe_value, resource);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::AccountMessage>::get_fields([[maybe_unused]] ::protoex_pmr::AccountMessage& fbe_value, [[maybe_unused]] std::pmr::memory_resource* resource) const noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.get(fbe_value.body, resource);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

size_t FinalModel<::protoex_pmr::AccountMessage>::set(const ::protoex_pmr::AccountMessage& fbe_value) noexcept
{
    _buffer.shift(fbe_offset());
    size_t fbe_result = set_fields(fbe_value);
    _buffer.unshift(fbe_offset());
    return fbe_result;
}

size_t FinalModel<::protoex_pmr::AccountMessage>::set_fields([[maybe_unused]] const ::protoex_pmr::AccountMessage& fbe_value) noexcept
{
    size_t fbe_current_offset = 0;
    size_t fbe_current_size = 0;
    [[maybe_unused]] size_t fbe_field_size;

    body.fbe_offset(fbe_current_offset);
    fbe_field_size = body.set(fbe_value.body);
    fbe_current_offset += fbe_field_size;
    fbe_current_size += fbe_field_size;

    return fbe_current_size;
}

namespace protoex_pmr {

bool AccountMessageFinalModel::verify()
{
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return false;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return false;

    return ((8 + _model.verify()) == fbe_struct_size);
}

size_t AccountMessageFinalModel::serialize(const ::protoex_pmr::AccountMessage& value)
{
    size_t fbe_initial_size = this->buffer().size();

    uint32_t fbe_struct_type = (uint32_t)fbe_type();
    uint32_t fbe_struct_size = (uint32_t)(8 + _model.fbe_allocation_size(value));
    uint32_t fbe_struct_offset = (uint32_t)(this->buffer().allocate(fbe_struct_size) - this->buffer().offset());
    assert(((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + fbe_struct_offset + fbe_struct_size) > this->buffer().size())
        return 0;

    fbe_struct_size = (uint32_t)(8 + _model.set(value));
    this->buffer().resize(fbe_initial_size + fbe_struct_size);

    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8, fbe_struct_size);
    unaligned_store<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4, fbe_struct_type);

    return fbe_struct_size;
}

size_t AccountMessageFinalModel::deserialize(::protoex_pmr::AccountMessage& value) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value);
}

size_t AccountMessageFinalModel::deserialize(::protoex_pmr::AccountMessage& value, std::pmr::memory_resource* resource) const noexcept
{
    assert(((this->buffer().offset() + _model.fbe_offset()) <= this->buffer().size()) && "Model is broken!");
    if ((this->buffer().offset() + _model.fbe_offset()) > this->buffer().size())
        return 0;

    size_t fbe_struct_size = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 8);
    size_t fbe_struct_type = unaligned_load<uint32_t>(this->buffer().data() + this->buffer().offset() + _model.fbe_offset() - 4);
    assert(((fbe_struct_size > 0) && (fbe_struct_type == fbe_type())) && "Model is broken!");
    if ((fbe_struct_size == 0) || (fbe_struct_type != fbe_type()))
        return 8;

    return 8 + _model.get(value, resource);
}

} // namespace protoex_pmr

} // namespace FBE
