//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: proto.fbe
// FBE version: 1.11.0.0
//------------------------------------------------------------------------------

#pragma once

#ifdef isset
#undef isset
#endif

#if defined(__clang__)
#pragma clang system_header
#elif defined(__GNUC__)
#pragma GCC system_header
#elif defined(_MSC_VER)
#pragma system_header
#endif

#include "fbe_final_models.h"

#include "proto_pmr.h"

namespace FBE {

// Fast Binary Encoding ::proto_pmr::OrderSide final model
template <>
class FinalModel<::proto_pmr::OrderSide> : public FinalModelBase<::proto_pmr::OrderSide, uint8_t>
{
public:
    using FinalModelBase<::proto_pmr::OrderSide, uint8_t>::FinalModelBase;
};

// Fast Binary Encoding ::proto_pmr::OrderType final model
template <>
class FinalModel<::proto_pmr::OrderType> : public FinalModelBase<::proto_pmr::OrderType, uint8_t>
{
public:
    using FinalModelBase<::proto_pmr::OrderType, uint8_t>::FinalModelBase;
};

// Fast Binary Encoding ::proto_pmr::State final model
template <>
class FinalModel<::proto_pmr::State> : public FinalModelBase<::proto_pmr::State, uint8_t>
{
public:
    using FinalModelBase<::proto_pmr::State, uint8_t>::FinalModelBase;
};

// Fast Binary Encoding ::proto_pmr::Order final model
template <>
class FinalModel<::proto_pmr::Order>
{
public:
    FinalModel(FBEBuffer& buffer, size_t offset) noexcept;

    // Get the allocation size
    size_t fbe_allocation_size(const ::proto_pmr::Order& fbe_value) const noexcept;
    // Get the final offset
    size_t fbe_offset() const noexcept { return _offset; }
    // Set the final offset
    size_t fbe_offset(size_t offset) const noexcept { return _offset = offset; }
    // Get the final type
    static constexpr size_t fbe_type() noexcept { return 1; }

    // Shift the current final offset
    void fbe_shift(size_t size) noexcept { _offset += size; }
    // Unshift the current final offset
    void fbe_unshift(size_t size) noexcept { _offset -= size; }

    // Check if the struct value is valid
    size_t verify() const noexcept;
    // Check if the struct fields are valid
    size_t verify_fields() const noexcept;

    // Get the struct value
    size_t get(::proto_pmr::Order& fbe_value) const noexcept;
    // Get the struct fields values
    size_t get_fields(::proto_pmr::Order& fbe_value) const noexcept;
    // Get the struct value with memory resource
    size_t get(::proto_pmr::Order& fbe_value, std::pmr::memory_resource* resource) const noexcept;
    // Get the struct fields values with memory resource
    size_t get_fields(::proto_pmr::Order& fbe_value, std::pmr::memory_resource* resource) const noexcept;

    // Set the struct value
    size_t set(const ::proto_pmr::Order& fbe_value) noexcept;
    // Set the struct fields values
    size_t set_fields(const ::proto_pmr::Order& fbe_value) noexcept;

private:
    FBEBuffer& _buffer;
    mutable size_t _offset;

public:
    FinalModel<int32_t> id;
    FinalModel<ArenaString> symbol;
    FinalModel<::proto_pmr::OrderSide> side;
    FinalModel<::proto_pmr::OrderType> type;
    FinalModel<double> price;
    FinalModel<double> volume;
};

namespace proto_pmr {

// Fast Binary Encoding Order final model
class OrderFinalModel : public FBE::Model
{
public:
    OrderFinalModel() : _model(this->buffer(), 8) {}
    OrderFinalModel(const std::shared_ptr<FBEBuffer>& buffer) : FBE::Model(buffer), _model(this->buffer(), 8) {}

    // Get the model type
    static constexpr size_t fbe_type() noexcept { return FinalModel<::proto_pmr::Order>::fbe_type(); }

    // Check if the struct value is valid
    bool verify();

    // Serialize the struct value
    size_t serialize(const ::proto_pmr::Order& value);
    // Deserialize the struct value
    size_t deserialize(::proto_pmr::Order& value) const noexcept;
    // Deserialize the struct value with memory resource
    size_t deserialize(::proto_pmr::Order& value, std::pmr::memory_resource* resource) const noexcept;

    // Move to the next struct value
    void next(size_t prev) noexcept { _model.fbe_shift(prev); }

private:
    FinalModel<::proto_pmr::Order> _model;
};

} // namespace proto_pmr

// Fast Binary Encoding ::proto_pmr::Balance final model
template <>
class FinalModel<::proto_pmr::Balance>
{
public:
    FinalModel(FBEBuffer& buffer, size_t offset) noexcept;

    // Get the allocation size
    size_t fbe_allocation_size(const ::proto_pmr::Balance& fbe_value) const noexcept;
    // Get the final offset
    size_t fbe_offset() const noexcept { return _offset; }
    // Set the final offset
    size_t fbe_offset(size_t offset) const noexcept { return _offset = offset; }
    // Get the final type
    static constexpr size_t fbe_type() noexcept { return 2; }

    // Shift the current final offset
    void fbe_shift(size_t size) noexcept { _offset += size; }
    // Unshift the current final offset
    void fbe_unshift(size_t size) noexcept { _offset -= size; }

    // Check if the struct value is valid
    size_t verify() const noexcept;
    // Check if the struct fields are valid
    size_t verify_fields() const noexcept;

    // Get the struct value
    size_t get(::proto_pmr::Balance& fbe_value) const noexcept;
    // Get the struct fields values
    size_t get_fields(::proto_pmr::Balance& fbe_value) const noexcept;
    // Get the struct value with memory resource
    size_t get(::proto_pmr::Balance& fbe_value, std::pmr::memory_resource* resource) const noexcept;
    // Get the struct fields values with memory resource
    size_t get_fields(::proto_pmr::Balance& fbe_value, std::pmr::memory_resource* resource) const noexcept;

    // Set the struct value
    size_t set(const ::proto_pmr::Balance& fbe_value) noexcept;
    // Set the struct fields values
    size_t set_fields(const ::proto_pmr::Balance& fbe_value) noexcept;

private:
    FBEBuffer& _buffer;
    mutable size_t _offset;

public:
    FinalModel<ArenaString> currency;
    FinalModel<double> amount;
};

namespace proto_pmr {

// Fast Binary Encoding Balance final model
class BalanceFinalModel : public FBE::Model
{
public:
    BalanceFinalModel() : _model(this->buffer(), 8) {}
    BalanceFinalModel(const std::shared_ptr<FBEBuffer>& buffer) : FBE::Model(buffer), _model(this->buffer(), 8) {}

    // Get the model type
    static constexpr size_t fbe_type() noexcept { return FinalModel<::proto_pmr::Balance>::fbe_type(); }

    // Check if the struct value is valid
    bool verify();

    // Serialize the struct value
    size_t serialize(const ::proto_pmr::Balance& value);
    // Deserialize the struct value
    size_t deserialize(::proto_pmr::Balance& value) const noexcept;
    // Deserialize the struct value with memory resource
    size_t deserialize(::proto_pmr::Balance& value, std::pmr::memory_resource* resource) const noexcept;

    // Move to the next struct value
    void next(size_t prev) noexcept { _model.fbe_shift(prev); }

private:
    FinalModel<::proto_pmr::Balance> _model;
};

} // namespace proto_pmr

// Fast Binary Encoding ::proto_pmr::Account final model
template <>
class FinalModel<::proto_pmr::Account>
{
public:
    FinalModel(FBEBuffer& buffer, size_t offset) noexcept;

    // Get the allocation size
    size_t fbe_allocation_size(const ::proto_pmr::Account& fbe_value) const noexcept;
    // Get the final offset
    size_t fbe_offset() const noexcept { return _offset; }
    // Set the final offset
    size_t fbe_offset(size_t offset) const noexcept { return _offset = offset; }
    // Get the final type
    static constexpr size_t fbe_type() noexcept { return 3; }

    // Shift the current final offset
    void fbe_shift(size_t size) noexcept { _offset += size; }
    // Unshift the current final offset
    void fbe_unshift(size_t size) noexcept { _offset -= size; }

    // Check if the struct value is valid
    size_t verify() const noexcept;
    // Check if the struct fields are valid
    size_t verify_fields() const noexcept;

    // Get the struct value
    size_t get(::proto_pmr::Account& fbe_value) const noexcept;
    // Get the struct fields values
    size_t get_fields(::proto_pmr::Account& fbe_value) const noexcept;
    // Get the struct value with memory resource
    size_t get(::proto_pmr::Account& fbe_value, std::pmr::memory_resource* resource) const noexcept;
    // Get the struct fields values with memory resource
    size_t get_fields(::proto_pmr::Account& fbe_value, std::pmr::memory_resource* resource) const noexcept;

    // Set the struct value
    size_t set(const ::proto_pmr::Account& fbe_value) noexcept;
    // Set the struct fields values
    size_t set_fields(const ::proto_pmr::Account& fbe_value) noexcept;

private:
    FBEBuffer& _buffer;
    mutable size_t _offset;

public:
    FinalModel<int32_t> id;
    FinalModel<ArenaString> name;
    FinalModel<::proto_pmr::State> state;
    FinalModel<::proto_pmr::Balance> wallet;
    FinalModel<std::optional<::proto_pmr::Balance>> asset;
    FinalModelVector<::proto_pmr::Order> orders;
};

namespace proto_pmr {

// Fast Binary Encoding Account final model
class AccountFinalModel : public FBE::Model
{
public:
    AccountFinalModel() : _model(this->buffer(), 8) {}
    AccountFinalModel(const std::shared_ptr<FBEBuffer>& buffer) : FBE::Model(buffer), _model(this->buffer(), 8) {}

    // Get the model type
    static constexpr size_t fbe_type() noexcept { return FinalModel<::proto_pmr::Account>::fbe_type(); }

    // Check if the struct value is valid
    bool verify();

    // Serialize the struct value
    size_t serialize(const ::proto_pmr::Account& value);
    // Deserialize the struct value
    size_t deserialize(::proto_pmr::Account& value) const noexcept;
    // Deserialize the struct value with memory resource
    size_t deserialize(::proto_pmr::Account& value, std::pmr::memory_resource* resource) const noexcept;

    // Move to the next struct value
    void next(size_t prev) noexcept { _model.fbe_shift(prev); }

private:
    FinalModel<::proto_pmr::Account> _model;
};

} // namespace proto_pmr

// Fast Binary Encoding ::proto_pmr::CharMap final model
template <>
class FinalModel<::proto_pmr::CharMap>
{
public:
    FinalModel(FBEBuffer& buffer, size_t offset) noexcept;

    // Get the allocation size
    size_t fbe_allocation_size(const ::proto_pmr::CharMap& fbe_value) const noexcept;
    // Get the final offset
    size_t fbe_offset() const noexcept { return _offset; }
    // Set the final offset
    size_t fbe_offset(size_t offset) const noexcept { return _offset = offset; }
    // Get the final type
    static constexpr size_t fbe_type() noexcept { return 1; }

    // Shift the current final offset
    void fbe_shift(size_t size) noexcept { _offset += size; }
    // Unshift the current final offset
    void fbe_unshift(size_t size) noexcept { _offset -= size; }

    // Check if the struct value is valid
    size_t verify() const noexcept;
    // Check if the struct fields are valid
    size_t verify_fields() const noexcept;

    // Get the struct value
    size_t get(::proto_pmr::CharMap& fbe_value) const noexcept;
    // Get the struct fields values
    size_t get_fields(::proto_pmr::CharMap& fbe_value) const noexcept;
    // Get the struct value with memory resource
    size_t get(::proto_pmr::CharMap& fbe_value, std::pmr::memory_resource* resource) const noexcept;
    // Get the struct fields values with memory resource
    size_t get_fields(::proto_pmr::CharMap& fbe_value, std::pmr::memory_resource* resource) const noexcept;

    // Set the struct value
    size_t set(const ::proto_pmr::CharMap& fbe_value) noexcept;
    // Set the struct fields values
    size_t set_fields(const ::proto_pmr::CharMap& fbe_value) noexcept;

private:
    FBEBuffer& _buffer;
    mutable size_t _offset;

public:
    FinalModelMap<char, ArenaString> abbr;
};

namespace proto_pmr {

// Fast Binary Encoding CharMap final model
class CharMapFinalModel : public FBE::Model
{
public:
    CharMapFinalModel() : _model(this->buffer(), 8) {}
    CharMapFinalModel(const std::shared_ptr<FBEBuffer>& buffer) : FBE::Model(buffer), _model(this->buffer(), 8) {}

    // Get the model type
    static constexpr size_t fbe_type() noexcept { return FinalModel<::proto_pmr::CharMap>::fbe_type(); }

    // Check if the struct value is valid
    bool verify();

    // Serialize the struct value
    size_t serialize(const ::proto_pmr::CharMap& value);
    // Deserialize the struct value
    size_t deserialize(::proto_pmr::CharMap& value) const noexcept;
    // Deserialize the struct value with memory resource
    size_t deserialize(::proto_pmr::CharMap& value, std::pmr::memory_resource* resource) const noexcept;

    // Move to the next struct value
    void next(size_t prev) noexcept { _model.fbe_shift(prev); }

private:
    FinalModel<::proto_pmr::CharMap> _model;
};

} // namespace proto_pmr

// Fast Binary Encoding ::proto_pmr::OrderMessage final model
template <>
class FinalModel<::proto_pmr::OrderMessage>
{
public:
    FinalModel(FBEBuffer& buffer, size_t offset) noexcept;

    // Get the allocation size
    size_t fbe_allocation_size(const ::proto_pmr::OrderMessage& fbe_value) const noexcept;
    // Get the final offset
    size_t fbe_offset() const noexcept { return _offset; }
    // Set the final offset
    size_t fbe_offset(size_t offset) const noexcept { return _offset = offset; }
    // Get the final type
    static constexpr size_t fbe_type() noexcept { return 2; }

    // Shift the current final offset
    void fbe_shift(size_t size) noexcept { _offset += size; }
    // Unshift the current final offset
    void fbe_unshift(size_t size) noexcept { _offset -= size; }

    // Check if the struct value is valid
    size_t verify() const noexcept;
    // Check if the struct fields are valid
    size_t verify_fields() const noexcept;

    // Get the struct value
    size_t get(::proto_pmr::OrderMessage& fbe_value) const noexcept;
    // Get the struct fields values
    size_t get_fields(::proto_pmr::OrderMessage& fbe_value) const noexcept;
    // Get the struct value with memory resource
    size_t get(::proto_pmr::OrderMessage& fbe_value, std::pmr::memory_resource* resource) const noexcept;
    // Get the struct fields values with memory resource
    size_t get_fields(::proto_pmr::OrderMessage& fbe_value, std::pmr::memory_resource* resource) const noexcept;

    // Set the struct value
    size_t set(const ::proto_pmr::OrderMessage& fbe_value) noexcept;
    // Set the struct fields values
    size_t set_fields(const ::proto_pmr::OrderMessage& fbe_value) noexcept;

private:
    FBEBuffer& _buffer;
    mutable size_t _offset;

public:
    FinalModel<::proto_pmr::Order> body;
};

namespace proto_pmr {

// Fast Binary Encoding OrderMessage final model
class OrderMessageFinalModel : public FBE::Model
{
public:
    OrderMessageFinalModel() : _model(this->buffer(), 8) {}
    OrderMessageFinalModel(const std::shared_ptr<FBEBuffer>& buffer) : FBE::Model(buffer), _model(this->buffer(), 8) {}

    // Get the model type
    static constexpr size_t fbe_type() noexcept { return FinalModel<::proto_pmr::OrderMessage>::fbe_type(); }

    // Check if the struct value is valid
    bool verify();

    // Serialize the struct value
    size_t serialize(const ::proto_pmr::OrderMessage& value);
    // Deserialize the struct value
    size_t deserialize(::proto_pmr::OrderMessage& value) const noexcept;
    // Deserialize the struct value with memory resource
    size_t deserialize(::proto_pmr::OrderMessage& value, std::pmr::memory_resource* resource) const noexcept;

    // Move to the next struct value
    void next(size_t prev) noexcept { _model.fbe_shift(prev); }

private:
    FinalModel<::proto_pmr::OrderMessage> _model;
};

} // namespace proto_pmr

// Fast Binary Encoding ::proto_pmr::BalanceMessage final model
template <>
class FinalModel<::proto_pmr::BalanceMessage>
{
public:
    FinalModel(FBEBuffer& buffer, size_t offset) noexcept;

    // Get the allocation size
    size_t fbe_allocation_size(const ::proto_pmr::BalanceMessage& fbe_value) const noexcept;
    // Get the final offset
    size_t fbe_offset() const noexcept { return _offset; }
    // Set the final offset
    size_t fbe_offset(size_t offset) const noexcept { return _offset = offset; }
    // Get the final type
    static constexpr size_t fbe_type() noexcept { return 3; }

    // Shift the current final offset
    void fbe_shift(size_t size) noexcept { _offset += size; }
    // Unshift the current final offset
    void fbe_unshift(size_t size) noexcept { _offset -= size; }

    // Check if the struct value is valid
    size_t verify() const noexcept;
    // Check if the struct fields are valid
    size_t verify_fields() const noexcept;

    // Get the struct value
    size_t get(::proto_pmr::BalanceMessage& fbe_value) const noexcept;
    // Get the struct fields values
    size_t get_fields(::proto_pmr::BalanceMessage& fbe_value) const noexcept;
    // Get the struct value with memory resource
    size_t get(::proto_pmr::BalanceMessage& fbe_value, std::pmr::memory_resource* resource) const noexcept;
    // Get the struct fields values with memory resource
    size_t get_fields(::proto_pmr::BalanceMessage& fbe_value, std::pmr::memory_resource* resource) const noexcept;

    // Set the struct value
    size_t set(const ::proto_pmr::BalanceMessage& fbe_value) noexcept;
    // Set the struct fields values
    size_t set_fields(const ::proto_pmr::BalanceMessage& fbe_value) noexcept;

private:
    FBEBuffer& _buffer;
    mutable size_t _offset;

public:
    FinalModel<::proto_pmr::Balance> body;
};

namespace proto_pmr {

// Fast Binary Encoding BalanceMessage final model
class BalanceMessageFinalModel : public FBE::Model
{
public:
    BalanceMessageFinalModel() : _model(this->buffer(), 8) {}
    BalanceMessageFinalModel(const std::shared_ptr<FBEBuffer>& buffer) : FBE::Model(buffer), _model(this->buffer(), 8) {}

    // Get the model type
    static constexpr size_t fbe_type() noexcept { return FinalModel<::proto_pmr::BalanceMessage>::fbe_type(); }

    // Check if the struct value is valid
    bool verify();

    // Serialize the struct value
    size_t serialize(const ::proto_pmr::BalanceMessage& value);
    // Deserialize the struct value
    size_t deserialize(::proto_pmr::BalanceMessage& value) const noexcept;
    // Deserialize the struct value with memory resource
    size_t deserialize(::proto_pmr::BalanceMessage& value, std::pmr::memory_resource* resource) const noexcept;

    // Move to the next struct value
    void next(size_t prev) noexcept { _model.fbe_shift(prev); }

private:
    FinalModel<::proto_pmr::BalanceMessage> _model;
};

} // namespace proto_pmr

// Fast Binary Encoding ::proto_pmr::AccountMessage final model
template <>
class FinalModel<::proto_pmr::AccountMessage>
{
public:
    FinalModel(FBEBuffer& buffer, size_t offset) noexcept;

    // Get the allocation size
    size_t fbe_allocation_size(const ::proto_pmr::AccountMessage& fbe_value) const noexcept;
    // Get the final offset
    size_t fbe_offset() const noexcept { return _offset; }
    // Set the final offset
    size_t fbe_offset(size_t offset) const noexcept { return _offset = offset; }
    // Get the final type
    static constexpr size_t fbe_type() noexcept { return 4; }

    // Shift the current final offset
    void fbe_shift(size_t size) noexcept { _offset += size; }
    // Unshift the current final offset
    void fbe_unshift(size_t size) noexcept { _offset -= size; }

    // Check if the struct value is valid
    size_t verify() const noexcept;
    // Check if the struct fields are valid
    size_t verify_fields() const noexcept;

    // Get the struct value
    size_t get(::proto_pmr::AccountMessage& fbe_value) const noexcept;
    // Get the struct fields values
    size_t get_fields(::proto_pmr::AccountMessage& fbe_value) const noexcept;
    // Get the struct value with memory resource
    size_t get(::proto_pmr::AccountMessage& fbe_value, std::pmr::memory_resource* resource) const noexcept;
    // Get the struct fields values with memory resource
    size_t get_fields(::proto_pmr::AccountMessage& fbe_value, std::pmr::memory_resource* resource) const noexcept;

    // Set the struct value
    size_t set(const ::proto_pmr::AccountMessage& fbe_value) noexcept;
    // Set the struct fields values
    size_t set_fields(const ::proto_pmr::AccountMessage& fbe_value) noexcept;

private:
    FBEBuffer& _buffer;
    mutable size_t _offset;

public:
    FinalModel<::proto_pmr::Account> body;
};

namespace proto_pmr {

// Fast Binary Encoding AccountMessage final model
class AccountMessageFinalModel : public FBE::Model
{
public:
    AccountMessageFinalModel() : _model(this->buffer(), 8) {}
    AccountMessageFinalModel(const std::shared_ptr<FBEBuffer>& buffer) : FBE::Model(buffer), _model(this->buffer(), 8) {}

    // Get the model type
    static constexpr size_t fbe_type() noexcept { return FinalModel<::proto_pmr::AccountMessage>::fbe_type(); }

    // Check if the struct value is valid
    bool verify();

    // Serialize the struct value
    size_t serialize(const ::proto_pmr::AccountMessage& value);
    // Deserialize the struct value
    size_t deserialize(::proto_pmr::AccountMessage& value) const noexcept;
    // Deserialize the struct value with memory resource
    size_t deserialize(::proto_pmr::AccountMessage& value, std::pmr::memory_resource* resource) const noexcept;

    // Move to the next struct value
    void next(size_t prev) noexcept { _model.fbe_shift(prev); }

private:
    FinalModel<::proto_pmr::AccountMessage> _model;
};

} // namespace proto_pmr

// Fast Binary Encoding ::proto_pmr::PremiumAccount final model
template <>
class FinalModel<::proto_pmr::PremiumAccount>
{
public:
    FinalModel(FBEBuffer& buffer, size_t offset) noexcept;

    // Get the allocation size
    size_t fbe_allocation_size(const ::proto_pmr::PremiumAccount& fbe_value) const noexcept;
    // Get the final offset
    size_t fbe_offset() const noexcept { return _offset; }
    // Set the final offset
    size_t fbe_offset(size_t offset) const noexcept { return _offset = offset; }
    // Get the final type
    static constexpr size_t fbe_type() noexcept { return 5; }

    // Shift the current final offset
    void fbe_shift(size_t size) noexcept { _offset += size; }
    // Unshift the current final offset
    void fbe_unshift(size_t size) noexcept { _offset -= size; }

    // Check if the struct value is valid
    size_t verify() const noexcept;
    // Check if the struct fields are valid
    size_t verify_fields() const noexcept;

    // Get the struct value
    size_t get(::proto_pmr::PremiumAccount& fbe_value) const noexcept;
    // Get the struct fields values
    size_t get_fields(::proto_pmr::PremiumAccount& fbe_value) const noexcept;
    // Get the struct value with memory resource
    size_t get(::proto_pmr::PremiumAccount& fbe_value, std::pmr::memory_resource* resource) const noexcept;
    // Get the struct fields values with memory resource
    size_t get_fields(::proto_pmr::PremiumAccount& fbe_value, std::pmr::memory_resource* resource) const noexcept;

    // Set the struct value
    size_t set(const ::proto_pmr::PremiumAccount& fbe_value) noexcept;
    // Set the struct fields values
    size_t set_fields(const ::proto_pmr::PremiumAccount& fbe_value) noexcept;

private:
    FBEBuffer& _buffer;
    mutable size_t _offset;

public:
    FinalModel<int32_t> id;
    FinalModel<ArenaString> name;
    FinalModel<ArenaString> info;
    FinalModel<::proto_pmr::Balance> private_wallet;
    FinalModelVector<::proto_pmr::Order> private_orders;
    FinalModel<::proto_pmr::State> private_state;
};

namespace proto_pmr {

// Fast Binary Encoding PremiumAccount final model
class PremiumAccountFinalModel : public FBE::Model
{
public:
    PremiumAccountFinalModel() : _model(this->buffer(), 8) {}
    PremiumAccountFinalModel(const std::shared_ptr<FBEBuffer>& buffer) : FBE::Model(buffer), _model(this->buffer(), 8) {}

    // Get the model type
    static constexpr size_t fbe_type() noexcept { return FinalModel<::proto_pmr::PremiumAccount>::fbe_type(); }

    // Check if the struct value is valid
    bool verify();

    // Serialize the struct value
    size_t serialize(const ::proto_pmr::PremiumAccount& value);
    // Deserialize the struct value
    size_t deserialize(::proto_pmr::PremiumAccount& value) const noexcept;
    // Deserialize the struct value with memory resource
    size_t deserialize(::proto_pmr::PremiumAccount& value, std::pmr::memory_resource* resource) const noexcept;

    // Move to the next struct value
    void next(size_t prev) noexcept { _model.fbe_shift(prev); }

private:
    FinalModel<::proto_pmr::PremiumAccount> _model;
};

} // namespace proto_pmr

} // namespace FBE
