sauce_connect: true
loopback: localhost
scripts:
  - "tests/*.js"
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: latest
  - name: microsoftedge
    version: latest
  - name: iphone
    version: latest
