name: Golang

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
        matrix:
          go-version: [1.20.x]
          os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: "Run tests"
        working-directory: projects/Go
        run: go test -v ./tests
      - name: "Run examples"
        working-directory: projects/Go
        run: go build && ./fbeproj
