name: MacOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: ${{false}}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup required packages'
        run: |
          ./pkg-dependency.sh
          echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH

      - name: 'Setup cmake'
        run: cmake --version

      - name: 'Setup git submodule'
        run: git submodule update --init --recursive

      - name: 'Build and test'
        run: |
          export CC=/usr/local/opt/llvm/bin/clang
          export CXX=/usr/local/opt/llvm/bin/clang++
          mkdir build.debug && cd build.debug
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
          ninja fbe-tests
          ./fbe-tests
